# name: Release
name: Release Geode Mod

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  release:
    name: Release mod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish release to index
        uses: hiimjasmine00/release-geode-mod@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          replace: false
          draft: false
          prerelease: false

  publish:
    name: Publish mod
    runs-on: ubuntu-latest
    needs: ["release"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish release to index
        uses: hiimjasmine00/release-geode-mod/publish@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
